### ISSUE TITLE
Get all sheets

### ISSUE THREAD

**Issue by sulram** [bpk68/g-sheets-api#1]
Is there a way to get all sheets of a spreadsheet?

**Comment by sulram** [comment]
anyway, thanks for the library!

**Comment by bpk68** [comment]
Hey @sulram, thanks for the message.  Completely sorry I missed this, but I'll take a look. Currently, I think because of the limitations of the way in which Google allow you to publish sheets, it's kind of a one-at-a-time deal.

I'll have a look and update this if I discover anything as we might be able to put a number of fetch operations in to go and grab a number of sheets and process them together. However, it'll depend on how Google let you publish things like this. 

I fear it might be a more complex use case for the official Sheets API, which requires licence keys and the full-blown Google API. 

I'll come back to you :)

**Comment by bpk68** [comment]
I'm going to close this as we've added the ability to fetch sheets by number now, so this should cover this need. There will have to be separate calls to achieve this, but it's doable now :D
