### ISSUE TITLE
Custom sheet name doesn't support + symbol(possibly others)

### ISSUE THREAD

**Issue by Kykuy** [bpk68/g-sheets-api#101]
If a sheet has a + in its name in any capacity, I get an error, even if I try to access it via index(sheetNumber). If I rename it to same name without + it works fine.
Didn't check for other mathematical/special symbols, but may well be the same case as well.

I didn't want to create a separate issue, but trying to access a 'normal' custom name sheet(without + in name, just latin letters) by sheetNumber without providing a correct sheetName doesn't seem to work as well, not sure if that is intended or a bug.

**Comment by bpk68** [comment]
Hey @Kykuy, thanks for raising an issue. It looks like there are two parts here:

1. You can't use '+' (and potentially other symbols in the sheet name,
2. You can't access a custom sheet name but the index alone.

The second is probably easier to answer first. If you're using a custom name for your sheet instead of the default (e.g. 'My Important Sheet Name' instead of 'Sheet1'), **then you'll have to use the `sheetName` option to give it the correct name**. Under the hood, the service calls a special Sheets URL from Google's own Sheets API that requires the name of the sheet. 
When this is the default (i.e. 'Sheet1', 'Sheet2', etc.) you can just pass in the sheet number and the package just appends this to the word 'Sheet', slotting it into the final URL. With a custom name, understandably that won't work anymore, so the full name of the sheet you want to access will be needed 👌🏻.

For the first issue, the symbols, I think this is slightly related to the other issue. Because we're ultimately stuffing the `sheetName` option into a URL, including symbols in the name means those symbols end up in the URL and that's possibly why it's failing. 

You could check in your browser's dev tools, under the network tab, to see which URL is being called and see if there's a problem with it there. 

I'll take a look if there's a solution here (we might be able to encode the `sheetName` so that the final URL is OK), but it might be that supporting custom sheet names with non-alphabetical characters is out 😬

**Comment by bpk68** [comment]
Good news 🎉 I've just pushed v2.1.1. 

Turns out it was a quick little enhancement there to encode the `sheetName` so that your special symbols should work. I tested it with a bunch of them in my test sheet and things look good. 

I'll caveat this by saying I can't guarantee _every_ symbol will work, but it should be looking good now 👍🏻
