### ISSUE TITLE
How to use with node.js?

### ISSUE THREAD

**Issue by Nabeel20** [bpk68/g-sheets-api#78]
I don't think the example is working? I got an empty object? everything is fine within browser. Thanks

**Comment by Majiedo** [comment]
1 - `npm install g-sheets-api --save-dev`



```
const options = {
  sheetId: 'id', // id of the sheet!
  sheetNumber: 1, // number of the sheet 
  returnAllResults: false, // if you want specific data  
  filter: { 
    'department': 'archaeology', 
    'module description': 'introduction'
  },
  filterOptions: {
    operator: 'or',
    matching: 'loose'
  }
}
```


**and then you can call the " options " if you wanna present it as html or whatever you want**

**Comment by bpk68** [comment]
Firstly, apologies for the tardy response to this, apparently GitHub notifies me about version bumps and dependency things, but not people who need some help or issues 🤦🏻‍♂️ So, thanks for bearing with me.

Sorry you're experiencing issues with the example @Nabeel20, and thanks for sharing some helpful info @Majiedo . 

@Nabeel20 I hate to play the classic developer's line of 'it's working on my machine', but it's working for me locally. If you can share a little more code or the sheet you're trying to access using the library then I can certainly help get you up and running.

Otherwise, I'll close the issue for now.

**Comment by Nabeel20** [comment]
Thank you :smile:
