### ISSUE TITLE
Column is missing in case of blank cell

### ISSUE THREAD

**Issue by jitendra1607** [bpk68/g-sheets-api#92]
Suppose I have 4 questions in a form and if 3rd question is optional to answer, so if any entry in a spreadsheet with an empty cell of 3rd column will be missing from reader resultant object. In this case there is no column key in object, but it is expected to have key present with null value.

Result (notice "Year / Stage" is missing from 2nd record of object)

`[
  {
    "Module Code" : "COM00001C-A",
    "Year / Stage" : "1",
    "Term Run": "Full Year"
  },
  {
    "Module Code" : "COM00002C-A",
    "Term Run": "Full Year"
  }
]`

Expected

`[
  {
    "Module Code" : "COM00001C-A",
    "Year / Stage" : "1",
    "Term Run": "Full Year"
  },
  {
    "Module Code" : "COM00002C-A",
    "Year / Stage" : Null,
    "Term Run": "Full Year"
  }
]`

**Comment by bpk68** [comment]
Hey @jitendra1607, thanks for flagging this. It's a nice flaw that Google Sheets has that it doesn't return a cell if the cell is empty 😠. Plus, all the returned results (that this package processes) are just cells...not full rows, so dealing with this is tricky. 

However, I've implemented a change for this so that the g-sheets-api returns `null` when the column/cell is empty. Basically, it'll work how you've highlighted in your 'expected' comments. 

I've pushed the latest release, `v1.4.3` now on here and npm so you should be able to grab it and do let me know if it's working out for you. 👍🏻
